### ISSUE TITLE
Final condition for the I2C host to be sure that sending or receiving has been successful

### ISSUE THREAD

**Issue by totolr** [microchip-pic-avr-examples/pic18f56q71-bare-metal-i2c-mplab#1]
Hello,
Thank you for your work ! Just in i2c_hosts.c at each end of function there is this line : 
```c
return (I2C1CNTL == 0);
```
But I2C1CNT can reach 0 but if there is an error to the last byte then I2C1CNT = 0, but there have been an error.
It isn't better to use CNTIF bit (of I2C1PIR register) because it is set when the last byte was properly receive or send.
That is an example :
```c
return I2C1PIRbits.CNTIF;
```
That is an image of one transmission, we can see the CNTIF to be set when whole communication was successful.
![image](https://github.com/microchip-pic-avr-examples/pic18f56q71-bare-metal-i2c-mplab/assets/53100486/77841b7c-ca79-441f-8359-3b9aa08e9044)

**Comment by totolr** [comment]
It's even written in the datasheet, I think is more robust like this. What do you think? I'd like to have your thoughts on this matter!
![image](https://github.com/microchip-pic-avr-examples/pic18f56q71-bare-metal-i2c-mplab/assets/53100486/33e5f99a-c80c-4929-93fa-92474f1a7863)

**Comment by pic-avr-github-admin** [comment]
Hi @totolr ,
We discussed the CNTIF flag versus the I2CxCNT method. They should be about equivalent - CNTIF is generated by the I2CxCNT register being equal to 0. The CNTIF flag is slightly more vulnerable than by I2CxCNT, as the CNTIF flag cannot be cleared by Hardware.
